version: 0.3.{build}
clone_folder: c:\projects\npackd-scripts
environment:
  matrix:
  - package: zlib-dev-i686-w64_4.9.2-static
    version: 1.2.11
init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-http-proxy.ps1'))
install:
- cmd.exe /C AppVeyorInstall.bat
build_script:
- cmd.exe /C AppVeyorBuild.bat
deploy:
  description: 'Automated release'
  provider: GitHub
  auth_token:
    secure: TZRXNYgUHwdfwkAfUimkaegIlCs5+UrAKl484ZCxAgvT5TmqA8TKd9nadxXHXDA0
  draft: true
  on:
    appveyor_repo_tag: true
