version: 0.3.{build}
clone_folder: c:\projects\npackd-scripts
environment:
  matrix:
# too slow for Appveyor - package: com.nokia.QtDev-i686-w64-Npackd-Release
#    version: 5.5
# too slow for Appveyor - package: com.nokia.QtDev-i686-w64-Npackd-Release
#    version: 5.5.1
# too slow for Appveyor - package: com.nokia.QtDev-i686-w64-Npackd-Release
#    version: 5.6
# too slow for Appveyor - package: com.nokia.QtDev-i686-w64-Npackd-Release
#    version: 5.7
# too slow for Appveyor - package: com.nokia.QtDev-i686-w64-Npackd-Release
#    version: 5.8
# too slow for Appveyor - package: com.nokia.QtDev-i686-w64-Npackd-Release
#    version: 5.9.2
# too slow for Appveyor - package: com.nokia.QtDev-x86_64-w64-Npackd-Release
#    version: 5.5
# too slow for Appveyor - package: com.nokia.QtDev-x86_64-w64-Npackd-Release
#    version: 5.5.1
# too slow for Appveyor - package: com.nokia.QtDev-x86_64-w64-Npackd-Release
#    version: 5.6
# too slow for Appveyor - package: com.nokia.QtDev-x86_64-w64-Npackd-Release
#    version: 5.7
# too slow for Appveyor - package: com.nokia.QtDev-x86_64-w64-Npackd-Release
#    version: 5.8
# too slow for Appveyor - package: com.nokia.QtDev-x86_64-w64-Npackd-Release
#    version: 5.9.2
# obsolete  - package: quazip-dev-i686-w64_sjlj_posix_4.9.2-qt_5.5-static
#    version: 0.7.1
# obsolete  - package: quazip-dev-i686-w64_sjlj_posix_4.9.2-qt_5.5-static
#    version: 0.7.3
# obsolete  - package: quazip-dev-i686-w64_sjlj_posix_7.1-qt_5.5-static
#    version: 0.7.3
  - package: quazip-dev-i686-w64_sjlj_posix_7.2-qt_5.9.2-static
    version: 0.7.3
  - package: quazip-dev-x86_64-w64_seh_posix_4.9.2-qt_5.5-static
    version: 0.7.1
# obsolete  - package: z-dev-i686-w64_sjlj_posix_4.9.2-static
#    version: 1.2.8
# obsolete  - package: z-dev-i686-w64_sjlj_posix_4.9.2-static
#    version: 1.2.11
  - package: z-dev-i686-w64_sjlj_posix_7.2-static
    version: 1.2.11
# obsolete  - package: z-dev-x86_64-w64_seh_posix_4.9.2-static
#    version: 1.2.11
  - package: z-dev-x86_64-w64_seh_posix_7.2-static
    version: 1.2.11
init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-http-proxy.ps1'))
install:
- cmd.exe /C AppVeyorInstall.bat
build_script:
- cmd.exe /C AppVeyorBuild.bat
deploy:
  description: 'Automated release'
  provider: GitHub
  auth_token:
    secure: TZRXNYgUHwdfwkAfUimkaegIlCs5+UrAKl484ZCxAgvT5TmqA8TKd9nadxXHXDA0
  draft: true
  on:
    appveyor_repo_tag: true
